#!/bin/bash

echo "========================================"
echo "Gemini APIキー設定チェック"
echo "========================================"
echo ""

# Vercelの環境変数を確認
echo "1. Vercel環境変数の確認:"
vercel env ls production | grep GEMINI

echo ""
echo "========================================"
echo "2. Gemini APIキーの設定方法:"
echo "========================================"
echo ""
echo "もしAPIキーが設定されていない、または正しく動作しない場合："
echo ""
echo "方法1: Vercelコマンドラインで設定"
echo "  vercel env add GEMINI_API_KEY production"
echo ""
echo "方法2: Vercelダッシュボードで設定"
echo "  1. https://vercel.com/yasuus-projects/business-card-manager/settings/environment-variables"
echo "  2. 'Add Environment Variable'をクリック"
echo "  3. Key: GEMINI_API_KEY"
echo "  4. Value: あなたのGemini APIキー"
echo "  5. Environment: Production にチェック"
echo "  6. 'Save'をクリック"
echo ""
echo "========================================"
echo "3. Gemini APIキーの取得方法:"
echo "========================================"
echo ""
echo "1. https://makersuite.google.com/app/apikey にアクセス"
echo "2. 'Create API Key'をクリック"
echo "3. 生成されたAPIキーをコピー"
echo ""
echo "========================================"
echo "4. デプロイの再実行:"
echo "========================================"
echo ""
echo "環境変数を設定した後、以下のコマンドで再デプロイ:"
echo "  vercel --prod --force"
echo ""