#!/bin/bash

echo "=========================================="
echo "Firebase 認証セットアップ"
echo "=========================================="
echo ""
echo "以下の方法から選択してください："
echo ""
echo "【方法1】Windows PowerShell/コマンドプロンプトで実行（推奨）"
echo "----------------------------------------"
echo "1. PowerShellを開く"
echo "2. 以下のコマンドを実行:"
echo ""
echo "   cd C:\\Users\\march\\n8n名刺管理\\business-card-manager"
echo "   firebase login"
echo ""
echo "3. ブラウザが開くので、Googleアカウントでログイン"
echo "4. ログイン成功後、以下を実行:"
echo ""
echo "   firebase deploy --only firestore:rules"
echo "   firebase deploy --only storage:rules"
echo ""
echo ""
echo "【方法2】Firebase Console で手動設定（最も簡単）"
echo "----------------------------------------"
echo "1. Firestore ルール設定:"
echo "   https://console.firebase.google.com/project/crypto-talon-417715/firestore/rules"
echo ""
echo "2. 以下のルールをコピーして貼り付け:"
cat firestore.rules
echo ""
echo "3. Storage ルール設定:"
echo "   https://console.firebase.google.com/project/crypto-talon-417715/storage/rules"
echo ""
echo "4. 以下のルールをコピーして貼り付け:"
cat storage.rules
echo ""
echo "=========================================="