#!/bin/bash

echo "========================================"
echo "Vercel環境変数の再設定"
echo "========================================"
echo ""
echo "改行文字が含まれている可能性があるため、環境変数を再設定します。"
echo ""

# 環境変数の値（.env.localから取得）
FIREBASE_API_KEY="AIzaSyDCbSPpCkCed3fRQDRbkwdfQcHCRfPV1Kg"
FIREBASE_AUTH_DOMAIN="crypto-talon-417715.firebaseapp.com"
FIREBASE_PROJECT_ID="crypto-talon-417715"
FIREBASE_STORAGE_BUCKET="crypto-talon-417715.appspot.com"
FIREBASE_MESSAGING_SENDER_ID="1039056244945"
FIREBASE_APP_ID="1:1039056244945:web:e67b9c4d047e547fd575f0"
FIREBASE_MEASUREMENT_ID="G-46D1QJKL5J"

echo "以下のコマンドを1つずつ実行してください："
echo ""
echo "# 既存の環境変数を削除"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_API_KEY production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_PROJECT_ID production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_APP_ID production"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID production"
echo ""
echo "# 環境変数を再追加"
echo "echo '$FIREBASE_API_KEY' | vercel env add NEXT_PUBLIC_FIREBASE_API_KEY production"
echo "echo '$FIREBASE_AUTH_DOMAIN' | vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production"
echo "echo '$FIREBASE_PROJECT_ID' | vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID production"
echo "echo '$FIREBASE_STORAGE_BUCKET' | vercel env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production"
echo "echo '$FIREBASE_MESSAGING_SENDER_ID' | vercel env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production"
echo "echo '$FIREBASE_APP_ID' | vercel env add NEXT_PUBLIC_FIREBASE_APP_ID production"
echo "echo '$FIREBASE_MEASUREMENT_ID' | vercel env add NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID production"
echo ""
echo "========================================"
echo "または、Vercelダッシュボードで手動設定："
echo "========================================"
echo ""
echo "1. https://vercel.com/yasuus-projects/business-card-manager/settings/environment-variables"
echo "2. 各環境変数を編集して、値に改行やスペースが含まれていないか確認"
echo "3. 特に AUTH_DOMAIN の値が正確に 'crypto-talon-417715.firebaseapp.com' であることを確認"
echo ""