#!/bin/bash

echo "================================================"
echo "Gemini API Key 設定修正スクリプト"
echo "================================================"
echo ""
echo "現在、VercelにGemini APIキーが設定されていません。"
echo "これが画像解析エラーの原因です。"
echo ""
echo "【設定方法】"
echo ""
echo "方法1: Vercel ダッシュボードから設定（推奨）"
echo "----------------------------------------------"
echo "1. 以下のURLにアクセス:"
echo "   https://vercel.com/yasuus-projects/business-card-manager/settings/environment-variables"
echo ""
echo "2. 「Add New」をクリック"
echo ""
echo "3. 以下を入力:"
echo "   - Name: GEMINI_API_KEY"
echo "   - Value: あなたのGemini APIキー"
echo "   - Environment: Production, Preview, Development 全てにチェック"
echo ""
echo "4. 「Save」をクリック"
echo ""
echo "5. デプロイし直す:"
echo "   vercel --prod"
echo ""
echo ""
echo "方法2: CLIから設定"
echo "----------------------------------------------"
echo "以下のコマンドを実行:"
echo ""
echo "1. APIキーを環境変数に追加:"
echo '   echo "あなたのAPIキー" | vercel env add GEMINI_API_KEY production'
echo '   echo "あなたのAPIキー" | vercel env add GEMINI_API_KEY preview'
echo '   echo "あなたのAPIキー" | vercel env add GEMINI_API_KEY development'
echo ""
echo "2. 再デプロイ:"
echo "   vercel --prod"
echo ""
echo ""
echo "【Gemini APIキーの取得】"
echo "----------------------------------------------"
echo "まだAPIキーをお持ちでない場合:"
echo "1. https://aistudio.google.com/app/apikey にアクセス"
echo "2. 「Create API Key」をクリック"
echo "3. 生成されたキーをコピー"
echo ""
echo "================================================"